# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Afcli < Formula
  desc "Agent-first CLI auditor for Claude skill descriptors."
  homepage "https://github.com/agentfirstcli/afcli"
  version "0.1.1-rc.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentfirstcli/afcli/releases/download/v0.1.1-rc.2/afcli_0.1.1-rc.2_darwin_amd64.tar.gz"
      sha256 "a629e4dc65d401d9dc3b3aed25b701d4c4ca89f57c460b7e08f0be6f1b9f0360"

      define_method(:install) do
        bin.install "afcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentfirstcli/afcli/releases/download/v0.1.1-rc.2/afcli_0.1.1-rc.2_darwin_arm64.tar.gz"
      sha256 "1c35c34689d680b5aba99a6c7169c55a5377669a67c3c6867d6a9381b5cfd2ca"

      define_method(:install) do
        bin.install "afcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentfirstcli/afcli/releases/download/v0.1.1-rc.2/afcli_0.1.1-rc.2_linux_amd64.tar.gz"
      sha256 "21d5db3aad25ba34ac5daff0ee61d2fce876af2e24dfe086bdec66ac65528485"
      define_method(:install) do
        bin.install "afcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentfirstcli/afcli/releases/download/v0.1.1-rc.2/afcli_0.1.1-rc.2_linux_arm64.tar.gz"
      sha256 "ef5b3e65bfd69e89a064a1fd837573f612e910b93a4c855a7c1b8e435cd003c1"
      define_method(:install) do
        bin.install "afcli"
      end
    end
  end

  test do
    system "#{bin}/afcli", "--version"
  end
end
