# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Afcli < Formula
  desc "Agent-first CLI auditor for Claude skill descriptors."
  homepage "https://github.com/agentfirstcli/afcli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentfirstcli/afcli/releases/download/v0.1.1/afcli_0.1.1_darwin_amd64.tar.gz"
      sha256 "e250aab37048d888f6a8f7e388bcab966ae89c0602e9becb522ce9cc87d836d3"

      define_method(:install) do
        bin.install "afcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentfirstcli/afcli/releases/download/v0.1.1/afcli_0.1.1_darwin_arm64.tar.gz"
      sha256 "9c7731608d94a5b12c00ea39cdab1f02aed38e38bcd1a34803c8f0dd1dd742de"

      define_method(:install) do
        bin.install "afcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentfirstcli/afcli/releases/download/v0.1.1/afcli_0.1.1_linux_amd64.tar.gz"
      sha256 "69b946601af49e52dc2ae86685d25528b26c13adf325bc8991bc0759b2c34f5b"
      define_method(:install) do
        bin.install "afcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentfirstcli/afcli/releases/download/v0.1.1/afcli_0.1.1_linux_arm64.tar.gz"
      sha256 "d2e154e4dc2572e718d0edcc1929a54d0c30a203c9ca8bfbb8e3a9fbf328890c"
      define_method(:install) do
        bin.install "afcli"
      end
    end
  end

  test do
    system "#{bin}/afcli", "--version"
  end
end
